### PR TITLE
:recycle: refactor autoequal_gen to use code_builder instead of Strings

### PR DESCRIPTION
**Pull request by techouse**
This PR converts autoequal_gen to use [code_builder](https://github.com/dart-lang/code_builder) rather than relying on Strings.

On top of that, I've also added a test workflow which will analyze both packages and run the tests in the test_project.

Please merge #20 before this.

### CODE REVIEW

**Comment by techouse** [comment]
@mrgnhnt96 once you're done with #20 check this one out :)

**Review by mrgnhnt96 — DISMISSED** [review]

**Comment by techouse** [comment]
@mrgnhnt96 you'll have to enable Github Actions in order to run the [test workflow](https://github.com/mrgnhnt96/autoequal/actions/workflows/test.yml)

**Comment by mrgnhnt96** [comment]
Ah, I just checked and everything was enabled, the only difference is that the default branch's name is not **master**, its **main**. I'll update the workflow

**Comment by techouse** [comment]
Oooooh, nice catch 😅

**Pull request merged**
