### PR TITLE
:arrow_up: updates

### PR DESCRIPTION
**Pull request by techouse**
- Bump version to 0.6.0
- Require Dart 3.0 or later
- Add final modifier to annotation classes
- Add final modifier to autoequal_generator classes
- Migrate from pedantic to lints
- Update dependencies

### CODE REVIEW

**Comment by techouse** [comment]
Fixes #19

**Comment by nuunoo1977** [comment]
Hi. Any idea when this merge request will be finished? Thanks

**Comment by wrbl606** [comment]
Hey @mrgnhnt96, any plans for publishing this? Is there something against it? If you're busy with something else that's fine, I can help with publishing this (and other changes/fixes) -- I just need proper access to this repo and pub.dev's [mrgnhnt.com](https://pub.dev/publishers/mrgnhnt.com) organisation access.

**Comment by mrgnhnt96** [comment]
👋 

Terribly sorry for the delay! TBH, I hadn't seen this PR yet. I'll go ahead and review it this morning and get it all merged in the morning 🙌 

Thanks for contributing 🤝

**Review by mrgnhnt96 — APPROVED** [review]

**Pull request merged**
