### PR TITLE
fix: `InterfaceType#element` -> `InterfaceType#element2`

### LINKED ISSUE #14: The getter 'element' isn't defined for the class 'InterfaceType'.
Looks like https://github.com/SunnyDayDev/autoequal/commit/1f4cd66138326d45c2837b3445a21d64841960c5 broke the generator when used with `analyzer: ^5.0.0`.

[`DartType.element` has been deprecated in v4.4.0](https://pub.dev/packages/analyzer/changelog#440) and [removed in v5.0.0](https://pub.dev/packages/analyzer/changelog#500). It will have to be migrated to `DartType.element2`.

I'll submit a PR later.

### PR DESCRIPTION
**Pull request by mrgnhnt96**
fixes: #14

### CODE REVIEW

**Review by SunnyDayDev — CHANGES_REQUESTED** [review]
After the refactoring, there was more than one place where the deprecated `element` API was called, exactly 4. I think all of them should be replaced by `element2`.

**Comment by mrgnhnt96** [comment]
Okay, I'll review the previous PR and make sure that I change them. This was the only one I distinctly remember changing, but I might've changed others. I'll have this PR ready by the morning

**Comment by SunnyDayDev** [comment]
Hey!

I checked the source code of `analyzer: 5.2.0` and it seems that `element2` is deprecated and `element` is restored. So it seems to be unnecessary changes.

```dart
  @Deprecated('Use element instead')
  @override
  InterfaceElement get element2;
```

Sorry for disturb.

**Comment by SunnyDayDev** [comment]
Oh, I understand what happened. `element` was deprecated in `4.7.0`, removed in `5.0.0` and restored in `5.2.0`. So sometime `element2` will be removed. In this case, do we need to support it? What do you think?

**Comment by mrgnhnt96** [comment]
If we update the dependencies to support min 5.2.0, do we still need to use element2? It might be resolved if we just bump the version.

In what use case does this error come up? It'd be great to have a test for this to prevent breaking it in the future

**Review by SunnyDayDev — APPROVED** [review]
Thanks for the fix

**Pull request merged**
